main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
 path('', views.home, name='home'),
 path('about/', views.about, name='about'),
 path('plants/', views.plants_index, name='index'),
 path('plants/<int:plant_id>/', views.plants_detail, name='detail'),
 path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
 path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plants_update'),
 path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plants_delete'),
 path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),

 path('fertilizers/', views.FertilizerList.as_view(), name='fertilizers_index'),
 path('fertilizers/<int:pk>/', views.FertilizerDetail.as_view(), name='fertilizers_detail'),
 path('fertilizers/create/', views.FertilizerCreate.as_view(), name='fertilizers_create'),
 path('fertilizers/<int:pk>/update/', views.FertilizerUpdate.as_view(), name='fertilizers_update'),
 path('fertilizers/<int:pk>/delete/', views.FertilizerDelete.as_view(), name='fertilizers_delete'),

path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),
# associate a toy with a cat (M:M)
path('plants/<int:plant_id>/assoc_fertilizer/<int:fertilizer_id>/', views.assoc_fertilizer, name='assoc_fertilizer'),
path('plants/<int:plant_id>/unassoc_fertilizer/<int:fertilizer_id>/', views.unassoc_fertilizer, name='unassoc_fertilizer'),

]

plantcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    
]

main_app/models.py
from django.db import models
from django.urls import reverse

WATERED = (
    ('M', 'Morning'),
    ('N', 'Night')
)
class Fertilizer(models.Model):
  name = models.CharField(max_length=50)
  type = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('fertilizers_detail', kwargs={'pk': self.id})

class Plant(models.Model): 
    species = models.CharField(max_length=100)
    hardiness = models.CharField(max_length=100) 
    description = models.TextField(max_length=250)
    fertilizers = models.ManyToManyField(Fertilizer)

    def __str__(self):
        return f'{self.species}({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'plant_id': self.id})

class Watering(models.Model):
    date = models.DateField('watering date')
    watered = models.CharField(max_length=1, choices=WATERED, default=WATERED[0][0])
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    plant = models.ForeignKey(
        Plant,
        on_delete=models.CASCADE
    )


    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_watered_display()} on {self.date}"
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm(ModelForm):
    class Meta: 
        model = Watering
        fields = ['date','watered']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Plant, Fertilizer
from .forms import WateringForm

'''plants = [
  {'species': 'Hibiscus', 'hardinessZones': '5-11', 'nativeArea': 'Asia, North America'},
  {'species': 'Jasmine', 'hardinessZones': '6-10', 'nativeArea': 'Eurasia, Africa, Australasia, Oceania'}
]
'''
# Create your views here.
# Define the home view
def assoc_fertilizer(request, plant_id, fertilizer_id):
  # Note that you can pass a toy's id instead of the whole toy object
  Plant.objects.get(id=plant_id).fertilizers.add(fertilizer_id)
  return redirect('detail', plant_id=plant_id)


def unassoc_fertilizer(request, plant_id, fertilizer_id):
  # Note that you can pass a toy's id instead of the whole toy object
  Plant.objects.get(id=plant_id).fertilizers.remove(fertilizer_id)
  return redirect('detail', plant_id=plant_id)



def home(request):
  # Include an .html file extension - unlike when rendering EJS templates
  return render(request, 'home.html')

def about(request):
    return render(request,'about.html')


def plants_index(request):
    plants = Plant.objects.all()
    return render(request, 'plants/index.html',{ 'plants': plants})

def plants_detail(request,plant_id):
    plant = Plant.objects.get(id=plant_id)
    id_list = plant.fertilizers.all().values_list('id')
    fertilizers_plant_doesnt_have = Fertilizer.objects.exclude(id__in=id_list)
    watering_form = WateringForm()
    return render(request, 'plants/detail.html', {'plant':plant, 'watering_form':watering_form, 'fertilizers':fertilizers_plant_doesnt_have})

def add_watering(request, plant_id):
 # create a ModelForm instance using the data in request.POST
  form = WateringForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_watering = form.save(commit=False)
    new_watering.plant_id = plant_id
    new_watering.save()
    return redirect('detail', plant_id=plant_id)


class PlantCreate(CreateView):
    model = Plant
    fields = '__all__'
success_url = '/plants/{plant_id}'

class PlantUpdate(UpdateView):
    model = Plant
    fields = ['hardiness','description']

class PlantDelete(DeleteView):
    model = Plant
    success_url = '/plants'

class FertilizerList(ListView):
  model = Fertilizer

class FertilizerDetail(DetailView):
  model = Fertilizer

class FertilizerCreate(CreateView):
  model = Fertilizer
  fields = '__all__'

class FertilizerUpdate(UpdateView):
  model = Fertilizer
  fields = ['name', 'type']

class FertilizerDelete(DeleteView):
  model = Fertilizer
  success_url = '/fertilizers'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Plant Collector</h1>
<hr>
<p>Plant Database of Awesome Plants!</p>
<footer>All Rights Reserved, © 2022 Plant Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Plant Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">  Plant Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'fertilizers_create' %}">Add a Fertilizer</a></li>
          <li><a href="{% url 'fertilizers_index' %}">View All Fertilizers</a></li>
          <li><a href="{% url 'plants_create' %}">Add a Plant</a></li>
          <li><a href="{% url 'index' %}">View All My Plants</a></li>


        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, © 2021 Plant Collector  </div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/fertilizer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Fertilizer</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'fertilizers_detail' fertilizer.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/fertilizer_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Fertilier Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ fertilizer.name }}</span>
        
      </div>
      <div class="card-action">
        <a href="{% url 'fertilizers_update' fertilizer.id %}">Edit</a>
        <a href="{% url 'fertilizers_delete' fertilizer.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/fertilizer_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Fertilizer</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/fertilizer_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Fertilizer List</h1>

{% for fertilizer in fertilizer_list %}
  <a href="{% url 'fertilizers_detail' fertilizer.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ fertilizer.name }}</span>
            <p>Type: {{ fertilizer.type }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Plant</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.species }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' plant.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.species}}</span></h1>
  {% else %}
    <h1>Add Plant</h1>
  {% endif %}
  
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Plant Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ plant.species }}</span>
    <p>Hardiness Zone: {{ plant.hardiness }}</p>
    <p>Description: {{ plant.description|linebreaks }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'plants_update' plant.id %}">Edit</a>
    <a href="{% url 'plants_delete' plant.id %}">Delete</a>
  </div>
  <div class="col s6">
    <form action="{% url 'add_watering' plant.id %}" method="POST">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ watering_form.as_p }}
        <input type="submit" class="btn" value="Add Watering">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Watered</th></tr>
      </thead>
      <tbody>
        {% for watering in plant.watering_set.all %}
          <tr>
            <td>{{watering.date}}</td>
            <td>{{watering.get_watered_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- This is all new markup to be added just above the <script> tag -->
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ plant.species }}'s Fertilizers</h3>
      {% if plant.fertilizers.count %}
        {% for fertilizer in plant.fertilizers.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                 <span style="type: {{ fertilizer.type }}">{{ fertilizer.type }}</span> {{ fertilizer.name }}
              </span>
            </div>

            <div class="card-action">
              <form action="{% url 'unassoc_fertilizer' plant.id fertilizer.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>

          </div>
        {% endfor %}
      {% else %}
        <h5>No Fertilizers 😿</h5>
      {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    <div class="col s6">
      <h3>Available Fertilizers</h3>
      {% if fertilizers.count %}
        {% for fertilizer in fertilizers.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                <span style="type: {{ fertilizer.type }}">{{ fertilizer.type }}</span> {{ fertilizer.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_fertilizer' plant.id fertilizer.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{plant.species}} Already Has All fetilizers Available</h5>
      {% endif %}
    </div>
  </div>
<script>
const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_watered');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Plant List</h1>

{% for plant in plants %}
  <div class="card">
    <a href="{% url 'detail' plant.id %}">
     <div class="card-content">
      <span class="card-title">{{ plant.name }}</span>
      <p>Species: {{ plant.species }}</p>
      <p>Hardiness Zone: {{ plant.hardiness }}</p>
      <p>Description: {{ plant.description }}</p>
     </div>
    </a>
  </div>
{% endfor %}

{% endblock %}